name: Build tt-native

on:
  push:
    branches:
      - main
      - v*-branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-tt-console:
    runs-on: ubuntu-22.04
    name: Build tt-console
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: tt-zephyr-platforms
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Fetch dependencies
        run: |
          pip install west
          west init -l tt-zephyr-platforms
          west update libjaylink

      - name: Run the script
        run: |
          cd tt-zephyr-platforms/scripts/tt-console
          ./build.sh
